
- name: check if Kubernetes has already been initialized.
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_stat

- name: kubeadm init
  shell: kubeadm init --apiserver-advertise-address={{ IP }} --cri-socket={{ CRI_SOCKET }} --pod-network-cidr=192.168.0.0/16  --ignore-preflight-errors=NumCPU,Mem
  when: not kubernetes_init_stat.stat.exists

- name: get the kubeadm join command from the Kubernetes master.
  command: kubeadm token create --print-join-command --ttl=1h
  register: kubernetes_join_command_result


- name: set the kubeadm join command globally.
  set_fact:
    kubernetes_join_command: "{{ kubernetes_join_command_result.stdout }}"
  when: kubernetes_join_command_result.stdout is defined
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"


- name: print join commnad
  debug:
    msg: "{{kubernetes_join_command}}"
  when: kubernetes_join_command_result.stdout is defined
  