
- include_tasks: hostname.yaml
  
- include_tasks: swap.yaml
  
- name: installing requires modules
  modprobe: 
    name: "{{item}}"
    state: present
  ignore_errors: yes
  with_items:
  - br_netfilter
  - overlay
  
- name: load br_netfilter module
  shell: modprobe br_netfilter 

- name: lchange sysctl config
  shell: echo '1' > {{item}}
  with_items:
    - /proc/sys/net/ipv4/ip_forward  
    - /proc/sys/net/bridge/bridge-nf-call-iptables

- name: ensure sysctl config permanently
  sysctl:
    name: "{{item}}"
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward

- name: disabling selinux
  shell: setenforce 0
  ignore_errors: true
  
- name: disabling selinux permanently
  shell: sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux

- include_tasks: firewall.yaml
