
- name: disabling selinux
  shell: setenforce 0
  ignore_errors: true
  
#- name: disabling selinux permanently
#  shell: sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux

- name: disable SELinux 
  configfile: /etc/sysconfig/selinux
  selinux:
    state: disabled
